fem: 
  polyOrder: 1 
  polyFamily: "Lagrange"

physics:
  kappa: 1.00e-6  # Coefficient of diffusivity
  alpha: 63.4     # Angle of stream
  beta_mag: 1.0   # Velocity magnitude of stream
  f: 0.0          # Source function magnitude 
 
boundary_conditions:
  strong:
    - tag: 1
      value: 1.0
    - tag: 2 
      value: 1.0
    - tag: 3 
      value: 0.0
    - tag: 4 
      value: 0.0 
    - tag: 5 
      value: 0.0
    
  weak: []

  inlet: [5]
  outlet: [3, 4]
    
Nitsche:
  gamma: -1.0
  C: 4.0

polynomials:
  polyOrder: 1
  polyFamily: "Lagrange"


  
